//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnologySolutions.AsciiProtocolSample.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM38")]
        public string ConnectPortName {
            get {
                return ((string)(this["ConnectPortName"]));
            }
            set {
                this["ConnectPortName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ResponseIsProtocolResponsePanelVisible {
            get {
                return ((bool)(this["ResponseIsProtocolResponsePanelVisible"]));
            }
            set {
                this["ResponseIsProtocolResponsePanelVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TransponderParametersIncludeTransponderRssi {
            get {
                return ((string)(this["TransponderParametersIncludeTransponderRssi"]));
            }
            set {
                this["TransponderParametersIncludeTransponderRssi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CommonParametersAccessPassword {
            get {
                return ((string)(this["CommonParametersAccessPassword"]));
            }
            set {
                this["CommonParametersAccessPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TransponderParametersIncludeChecksum {
            get {
                return ((string)(this["TransponderParametersIncludeChecksum"]));
            }
            set {
                this["TransponderParametersIncludeChecksum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ResponseParametersIncludeDateTime {
            get {
                return ((string)(this["ResponseParametersIncludeDateTime"]));
            }
            set {
                this["ResponseParametersIncludeDateTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TransponderParametersIncludeIndex {
            get {
                return ((string)(this["TransponderParametersIncludeIndex"]));
            }
            set {
                this["TransponderParametersIncludeIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TransponderParametersIncludePC {
            get {
                return ((string)(this["TransponderParametersIncludePC"]));
            }
            set {
                this["TransponderParametersIncludePC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AntennaParametersOutputPower {
            get {
                return ((string)(this["AntennaParametersOutputPower"]));
            }
            set {
                this["AntennaParametersOutputPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ResponseParametersUseAlert {
            get {
                return ((string)(this["ResponseParametersUseAlert"]));
            }
            set {
                this["ResponseParametersUseAlert"] = value;
            }
        }
    }
}
